### ISSUE TITLE
DoS by passing TMPDIR in env

### ISSUE THREAD

**Issue by drahnr** [paritytech/sccache#20]
For the dist case, it seems that a single user can provide a TMPDIR env var, which will cause the dist server to fail creating such a temp directory.

Upstream: https://github.com/mozilla/sccache/issues/837

**Comment by Xanewok** [comment]
I was just browsing the code and noticed that the TMPDIR seems to be cleared in the dist compilation request: https://github.com/mozilla/sccache/blob/3f318a8675e4c3de4f5e8ab2d086189f2ae5f5cf/src/compiler/rust.rs#L1597-L1600 Leaving this for posterity. Maybe there's a different code path that's not accounted for and/or this doesn't what it's supposed to?

**Comment by drahnr** [comment]
Good catch! I'll close this then, the original issue is either non-dist specific as read it.
